### ISSUE TITLE
Text input misplaced (shown twice)

### ISSUE THREAD

**Issue by AlexanderWillner** [mikker/YosemiteInterface-qsplugin#3]
Description: Text input misplaced (shown twice)
Version: 1.0.1

Steps that will reproduce the problem?
1. Invoke QS
2. Press "."
3. Type text

What is the expected result?
Nice visualisation of the typed text.

What happens instead?
Text is shown twice.
## Possible workaround:

Any additional information:
See screenshot.
![screen shot 2014-06-23 at 23 41 18](https://cloud.githubusercontent.com/assets/307605/3364417/3980d8cc-fb1f-11e3-9a64-9ad3cfb1c668.png)

**Comment by pjrobertson** [comment]
This has been fixed over in my repo here:
![Screen Region 2022-06-19 at 17 52 47](https://user-images.githubusercontent.com/150431/174475458-b4dcad29-67b6-4123-af0f-2945eb2bc81b.png)


I hope we can release this interface as an officially supported QS interface soon. It really is the best looking interface QS has!

**Comment by pjrobertson** [comment]
This is fixed in v2.0 of the Yosemite plugin, available to download within Quicksilver.

@mikker - I think you can close this now :)
